"""
This type stub file was generated by pyright.
"""

from google.resumable_media import (
    DataCorruption as DataCorruptionDynamicParent,
    InvalidResponse as InvalidResponseDynamicParent,
)

"""Exceptions raised by the library."""

class InvalidResponse(InvalidResponseDynamicParent):
    """Error class for responses which are not in the correct state.

    Args:
        response (object): The HTTP response which caused the failure.
        args (tuple): The positional arguments typically passed to an
            exception class.
    """
    def __init__(self, response, *args) -> None: ...

class DataCorruption(DataCorruptionDynamicParent):
    """Error class for corrupt media transfers.

    Args:
        response (object): The HTTP response which caused the failure.
        args (tuple): The positional arguments typically passed to an
            exception class.
    """
    def __init__(self, response, *args) -> None: ...
