name: Extract IPSW symbols
on:
  workflow_dispatch:
  schedule:
   - cron: "55 */6 * * *"

concurrency: ipsw_extract

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/symx/runner/macos.yml
    with:
      job_name: Extract IPSW symbols
      symx_step: IPSW Extract
      symx_run: |
          export PATH="/Users/runner/.local/bin:$PATH"
          poetry run symx -v ipsw extract -t 315 -s ${{ vars.SYMX_STORE }}