name: 'Init gcloud action'
description: 'Setups authentication and tooling for gcloud'
runs:
  using: 'composite'
  steps:
    - name: Auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/868781662168/locations/global/workloadIdentityPools/prod-github/providers/github-oidc-pool
        service_account: symx-downloader@sac-prod-sa.iam.gserviceaccount.com

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: ">= 363.0.0"