name: symx on Ubuntu

on:
  workflow_call:
    inputs:
      job_name:
        required: true
        type: string
      symx_step:
        required: true
        type: string
      symx_run:
        required: true
        type: string

jobs:
  symx-ubuntu-job:
    name: ${{ inputs.job_name }}
    runs-on: "ubuntu-22.04"
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Init workflow
        uses: ./.github/actions/init_symx.yml

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e ./ 

      - name: Install Apple Inc. Root
        run: |
          wget https://www.apple.com/appleca/AppleIncRootCertificate.cer
          openssl x509 -inform DER -in AppleIncRootCertificate.cer -out AppleIncRootCertificate.crt
          sudo cp AppleIncRootCertificate.crt /usr/local/share/ca-certificates
          sudo update-ca-certificates

      - name: ${{ inputs.symx_step }}
        run: ${{ inputs.symx_run }}
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
