name: 'List bucket contents'

on:
  workflow_dispatch:
    inputs:
      gs_cli_parameters:
        description: 'gcloud storage ls parameters'
        required: true
        default: '-r -a -L gs://sentryio-symx-symbols-0'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/bucket-runner.yml
    with:
      job_name: 'List bucket contents'
      bucket_step: 'List bucket contents'
      bucket_run: 'gcloud storage ls ${{ github.event.inputs.gs_cli_parameters }} '
