name: Code checks
permissions:
  contents: read
  pull-requests: read

on: [ push, pull_request ]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "PATH=/Users/runner/.local/bin:$PATH" >> $GITHUB_ENV
      - name: uv version
        run: uv --version
      - name: uv sync
        run: uv sync
      - name: ruff
        run: uv run ruff check symx
      - name: ruff format
        run: uv run ruff format --check
      - name: pyright
        run: uv run pyright
      - name: pytest
        run: uv run pytest
