name: Code checks
on: [ push, pull_request ]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - name: ruff
        run: poetry run ruff check symx
      - name: black
        run: poetry run black symx --check
      - name: mypy
        run: poetry run mypy --install-types --non-interactive
      - name: pytest
        run: poetry run pytest
