name: Code checks
permissions:
  contents: read
  pull-requests: read

on: [ push, pull_request ]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install dependencies
        run: |
          source .github/scripts/bootstrap-uv.sh
      - name: uv version
        run: uv --version
      - name: uv sync
        run: uv sync
      - name: ruff
        run: uv run ruff check
      - name: ruff format
        run: uv run ruff format --check
      - name: pyright
        run: uv run pyright
      - name: pytest
        run: uv run pytest
