name: Code checks
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: poetry run ruff check symx
      - run: poetry run black --check
      - run: poetry run mypy
