name: Code checks
on: [ push, pull_request ]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - name: ruff
        run: poetry run ruff check symx
      - name: ruff format
        run: poetry run ruff format --check
      - name: mypy
        run: poetry run pyright
      - name: pytest
        run: poetry run pytest
