name: Migrate IPSW storage
on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/symx_ubuntu.yml
    with:
      job_name: Migrate IPSW storage
      symx_step: IPSW migrate-storage
      symx_run: symx -v ipsw migrate -s ${{ vars.SYMX_STORE }}