name: Mirror OTA images
on:
  workflow_dispatch:
  schedule:
    - cron: "30 */6 * * *"

concurrency: ota_mirror

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/symx-runner-ubuntu.yml
    with:
      job_name: Mirror OTA images
      symx_step: OTA Mirror
      symx_run: symx -v ota mirror -s ${{ vars.SYMX_STORE }}
    secrets: inherit