name: Extract OTA symbols
permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
  schedule:
   - cron: "30 */6 * * *"

concurrency: ota_extract

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/symx-runner-macos.yml
    with:
      job_name: Extract OTA symbols
      symx_step: OTA Extract
      symx_run: -v ota extract -t 330 -s ${{ vars.SYMX_STORE }}
    secrets:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}