name: Sync IPSW meta-db
on:
  workflow_dispatch:
  schedule:
    - cron: "45 4 * * *"

concurrency: ipsw_meta_sync

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/symx-runner-ubuntu.yml
    with:
      job_name: Sync IPSW meta
      symx_step: IPSW meta-sync
      symx_run: symx -v ipsw meta-sync -s ${{ vars.SYMX_STORE }}
    secrets: inherit