name: Migrate IPSW storage
permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/symx-runner-ubuntu.yml
    with:
      job_name: Migrate IPSW storage
      symx_step: IPSW migrate-storage
      symx_run: -v ipsw migrate -s ${{ vars.SYMX_STORE }}
    secrets:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}